"""Rebuild graph (Level 1): outer epic loop.

Loads the backlog from epics.md, initializes the target project, then
iterates through each epic by invoking the EpicGraph (Level 2) as a
wrapper node. After each epic completes, tags the git repo and advances
to the next epic. Writes a final rebuild-status.md summary when all
epics are done.

Uses SQLite checkpointing so the rebuild can resume from the last
completed epic after a crash.
"""

from __future__ import annotations

import logging
import operator
import os
import sqlite3
import subprocess
import time
from typing import Annotated, Any, TypedDict

from langgraph.checkpoint.sqlite import SqliteSaver
from langgraph.graph import END, START, StateGraph
from langgraph.graph.state import CompiledStateGraph

from src.intake.backlog import load_backlog
from src.intake.epic_graph import EpicState, build_epic_runner

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# State Schema
# ---------------------------------------------------------------------------


class RebuildState(TypedDict, total=False):
    """State schema for the rebuild graph (Level 1).

    Manages epic iteration and accumulates results from all epics.
    """

    # Identity
    session_id: str
    target_dir: str

    # Epic iteration
    epics: list[dict[str, Any]]  # [{name: str, stories: [dict]}, ...]
    epic_index: int
    total_stories: int

    # Accumulated across all epics
    all_story_results: Annotated[list[dict[str, Any]], operator.add]
    stories_completed: int
    stories_failed: int
    total_interventions: int

    # Current epic output
    current_epic_status: str  # completed|failed|aborted
    current_epic_error: str

    # Control
    pipeline_status: str  # running|completed|failed|aborted
    error: str
    start_time: float


# ---------------------------------------------------------------------------
# Nodes
# ---------------------------------------------------------------------------


def load_backlog_node(state: RebuildState) -> dict[str, Any]:
    """Parse epics.md and group stories by epic."""
    target_dir = state.get("target_dir", "")

    backlog = load_backlog(target_dir)

    # Group by epic, preserving order
    groups: dict[str, list[dict[str, Any]]] = {}
    for entry in backlog:
        epic = str(entry.get("epic", ""))
        if epic not in groups:
            groups[epic] = []
        groups[epic].append(entry)

    epics = [{"name": name, "stories": stories} for name, stories in groups.items()]

    total_stories = sum(len(e["stories"]) for e in epics)

    logger.info("Loaded backlog: %d epics, %d stories", len(epics), total_stories)

    return {
        "epics": epics,
        "epic_index": 0,
        "total_stories": total_stories,
        "all_story_results": [],
        "stories_completed": 0,
        "stories_failed": 0,
        "total_interventions": 0,
        "pipeline_status": "running",
        "start_time": time.time(),
    }


def init_project_node(state: RebuildState) -> dict[str, Any]:
    """Initialize the target project directory with git repo and scaffold."""
    target_dir = state.get("target_dir", "")
    os.makedirs(target_dir, exist_ok=True)

    git_dir = os.path.join(target_dir, ".git")
    if not os.path.exists(git_dir):
        subprocess.run(
            ["git", "init"],
            cwd=target_dir,
            capture_output=True,
            text=True,
            check=True,
        )
        subprocess.run(
            ["git", "config", "user.name", "Shipyard"],
            cwd=target_dir,
            capture_output=True,
            check=True,
        )
        subprocess.run(
            ["git", "config", "user.email", "shipyard@localhost"],
            cwd=target_dir,
            capture_output=True,
            check=True,
        )

        readme_path = os.path.join(target_dir, "README.md")
        if not os.path.exists(readme_path):
            with open(readme_path, "w", encoding="utf-8") as f:
                f.write("# Target Project\n\nGenerated by Shipyard.\n")

        subprocess.run(
            ["git", "add", "."],
            cwd=target_dir,
            capture_output=True,
            check=True,
        )
        subprocess.run(
            ["git", "commit", "-m", "chore: initial project scaffold"],
            cwd=target_dir,
            capture_output=True,
            text=True,
            check=True,
        )

    return {}


def select_epic_node(state: RebuildState) -> dict[str, Any]:
    """Prepare state for the current epic."""
    epics = state.get("epics", [])
    epic_index = state.get("epic_index", 0)
    epic = epics[epic_index]

    logger.info("Starting epic %d/%d: %s", epic_index + 1, len(epics), epic["name"])

    return {
        "current_epic_status": "",
        "current_epic_error": "",
    }


def run_epic_node(state: RebuildState) -> dict[str, Any]:
    """Invoke the EpicGraph (Level 2) for the current epic.

    This is a wrapper node — it builds EpicState from RebuildState,
    invokes the compiled epic graph, and maps the results back.
    """
    session_id = state.get("session_id", "")
    target_dir = state.get("target_dir", "")
    epics = state.get("epics", [])
    epic_index = state.get("epic_index", 0)
    epic = epics[epic_index]

    epic_input: EpicState = {
        "session_id": session_id,
        "target_dir": os.path.abspath(target_dir),
        "epic_name": epic["name"],
        "stories": epic["stories"],
        "story_index": 0,
        "story_results": [],
        "stories_completed": 0,
        "stories_failed": 0,
        "total_interventions": 0,
        "epic_files_modified": [],
        "current_story_status": "",
        "current_story_error": "",
        "current_story_retry_instruction": "",
        "epic_review_file_paths": [],
        "epic_fix_plan_path": "",
        "epic_fixes_needed": False,
        "epic_fix_cycle": 0,
        "epic_test_passed": False,
        "epic_last_test_output": "",
        "epic_last_ci_output": "",
        "epic_status": "running",
        "error": "",
    }

    compiled_epic = build_epic_runner()

    try:
        result = compiled_epic.invoke(epic_input)
        result = dict(result)
    except Exception as e:
        logger.exception("Epic graph failed for %s: %s", epic["name"], e)
        result = {
            "epic_status": "failed",
            "error": str(e),
            "story_results": [],
            "stories_completed": 0,
            "stories_failed": 0,
            "total_interventions": 0,
        }

    epic_status = result.get("epic_status", "failed")
    story_results = result.get("story_results", [])
    epic_completed = result.get("stories_completed", 0)
    epic_failed = result.get("stories_failed", 0)
    epic_interventions = result.get("total_interventions", 0)

    return {
        "current_epic_status": epic_status,
        "current_epic_error": result.get("error", ""),
        "all_story_results": story_results,
        "stories_completed": state.get("stories_completed", 0) + epic_completed,
        "stories_failed": state.get("stories_failed", 0) + epic_failed,
        "total_interventions": state.get("total_interventions", 0) + epic_interventions,
    }


def tag_epic_node(state: RebuildState) -> dict[str, Any]:
    """Create a git tag marking epic completion."""
    target_dir = state.get("target_dir", "")
    epics = state.get("epics", [])
    epic_index = state.get("epic_index", 0)
    epic_name = epics[epic_index]["name"]

    tag_name = f"epic-{epic_name.replace(' ', '-').lower()}-complete"
    result = subprocess.run(
        ["git", "tag", tag_name],
        cwd=target_dir,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        logger.warning("Git tag '%s' failed: %s", tag_name, result.stderr.strip())
    else:
        logger.info("Tagged epic completion: %s", tag_name)

    return {}


def write_status_node(state: RebuildState) -> dict[str, Any]:
    """Write rebuild-status.md after the current epic."""
    target_dir = state.get("target_dir", "")
    story_results = state.get("all_story_results", [])
    total_stories = state.get("total_stories", 0)
    total_interventions = state.get("total_interventions", 0)

    _write_rebuild_status(
        target_dir=target_dir,
        story_results=story_results,
        total_stories=total_stories,
        total_interventions=total_interventions,
    )

    return {}


def advance_epic_node(state: RebuildState) -> dict[str, Any]:
    """Advance epic_index to the next epic."""
    return {"epic_index": state.get("epic_index", 0) + 1}


def write_final_node(state: RebuildState) -> dict[str, Any]:
    """Write final rebuild-status.md with timing and set terminal status."""
    target_dir = state.get("target_dir", "")
    story_results = state.get("all_story_results", [])
    total_stories = state.get("total_stories", 0)
    total_interventions = state.get("total_interventions", 0)
    start_time = state.get("start_time", time.time())
    stories_failed = state.get("stories_failed", 0)

    elapsed = time.time() - start_time

    _write_rebuild_status(
        target_dir=target_dir,
        story_results=story_results,
        total_stories=total_stories,
        total_interventions=total_interventions,
        elapsed_seconds=elapsed,
        is_final=True,
    )

    status = "completed" if stories_failed == 0 else "failed"
    if state.get("current_epic_status") == "aborted":
        status = "aborted"

    logger.info("Rebuild %s: %d/%d stories completed in %.1f minutes",
                status, state.get("stories_completed", 0), total_stories, elapsed / 60)

    return {
        "pipeline_status": status,
    }


# ---------------------------------------------------------------------------
# Routing
# ---------------------------------------------------------------------------


def route_after_epic(state: RebuildState) -> str:
    """Route after epic completes: more epics, aborted, or done."""
    epic_status = state.get("current_epic_status", "")

    if epic_status == "aborted":
        return "aborted"

    epics = state.get("epics", [])
    epic_index = state.get("epic_index", 0)

    if epic_index + 1 < len(epics):
        return "more_epics"

    return "all_done"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _write_rebuild_status(
    target_dir: str,
    story_results: list[dict[str, Any]],
    total_stories: int,
    total_interventions: int,
    elapsed_seconds: float | None = None,
    is_final: bool = False,
) -> None:
    """Write rebuild-status.md to the target directory."""
    completed = sum(1 for r in story_results if r.get("status") == "completed")
    failed = sum(1 for r in story_results if r.get("status") != "completed")

    lines = ["# Ship App Rebuild Status\n"]

    current_epic = ""
    for result in story_results:
        epic = result.get("epic", "")
        if epic != current_epic:
            lines.append(f"\n## Epic: {epic}\n")
            current_epic = epic

        status = result.get("status", "unknown")
        interventions = result.get("interventions", 0)
        suffix = f" (intervention #{interventions})" if interventions > 0 else ""
        lines.append(f"- Story: {result.get('story', '?')} — {status}{suffix}")

    lines.append("\n## Summary\n")
    lines.append(f"Stories completed: {completed}/{total_stories}")
    lines.append(f"Stories failed: {failed}")
    lines.append(f"Interventions: {total_interventions}")

    if is_final and elapsed_seconds is not None:
        minutes = elapsed_seconds / 60
        lines.append(f"Total time: {minutes:.1f} minutes")

    status_path = os.path.join(target_dir, "rebuild-status.md")
    with open(status_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


# ---------------------------------------------------------------------------
# Graph Construction
# ---------------------------------------------------------------------------


def build_rebuild_graph() -> StateGraph:  # type: ignore[type-arg]
    """Build the rebuild graph (Level 1).

    Flow:
    load_backlog → init_project → select_epic → run_epic →
    tag_epic → write_status → route
        → (more_epics) → advance_epic → select_epic
        → (aborted) → write_final → END
        → (all_done) → write_final → END

    Returns:
        Uncompiled StateGraph.
    """
    graph = StateGraph(RebuildState)

    # Nodes
    graph.add_node("load_backlog", load_backlog_node)
    graph.add_node("init_project", init_project_node)
    graph.add_node("select_epic", select_epic_node)
    graph.add_node("run_epic", run_epic_node)
    graph.add_node("tag_epic", tag_epic_node)
    graph.add_node("write_status", write_status_node)
    graph.add_node("advance_epic", advance_epic_node)
    graph.add_node("write_final", write_final_node)

    # Edges
    graph.add_edge(START, "load_backlog")
    graph.add_edge("load_backlog", "init_project")
    graph.add_edge("init_project", "select_epic")
    graph.add_edge("select_epic", "run_epic")
    graph.add_edge("run_epic", "tag_epic")
    graph.add_edge("tag_epic", "write_status")

    graph.add_conditional_edges(
        "write_status",
        route_after_epic,
        {
            "more_epics": "advance_epic",
            "aborted": "write_final",
            "all_done": "write_final",
        },
    )

    graph.add_edge("advance_epic", "select_epic")
    graph.add_edge("write_final", END)

    return graph


def build_rebuild(
    checkpoints_db: str = "checkpoints/rebuild.db",
) -> CompiledStateGraph[Any]:
    """Build and compile the rebuild graph with SQLite checkpointing.

    Args:
        checkpoints_db: Path to SQLite database for checkpointing.

    Returns:
        CompiledGraph ready for invocation.
    """
    graph = build_rebuild_graph()
    os.makedirs(os.path.dirname(checkpoints_db), exist_ok=True)
    conn = sqlite3.connect(checkpoints_db, check_same_thread=False)
    memory = SqliteSaver(conn)
    return graph.compile(checkpointer=memory)
