#!/bin/bash
#
# code-review-analysis-fix - Analyze Code Review Results and Apply Fixes
#
# Seven-phase workflow:
#   Phase 0 (REVIEW):    Run both code review scripts (BMAD + Claude in parallel)
#   Phase 1 (ANALYZE):   Compare BMAD and Claude code review results, create fix plan
#   Phase 2 (FIX):       Apply clear, non-controversial fixes from the plan
#   Phase 3 (ARCHITECT): Generate architect recommendations for controversial items
#   Phase 4 (ARCH-FIX):  Apply fixes from architect's fix plan
#   Phase 5 (CI):        Run CI pipeline (scripts/local_ci.sh) with auto-fix retry loop
#   Phase 6 (GIT):       Create local git commit with pre-commit hook handling
#
# Input files (from code-review-loop scripts, or auto-generated by review phase):
#   - epic<N>-code-review-bmad-results.log
#   - epic<N>-code-review-claude-results.log
#
# Output files:
#   - epic<N>-code-review-analysis.md       (analysis with agent comparison table)
#   - epic<N>-code-review-fix-plan.md        (clear fixes only - Phase 2 input)
#   - epic<N>-code-review-fix-plan-done.md  (execution log with timestamps - Phase 2 output)
#   - epic<N>-architect-review-needed.md    (controversial items + skipped items - Phase 3 input)
#   - epic<N>-architect-recommendations.md   (architect decisions - Phase 3 output)
#   - epic<N>-architect-fix-plan.md          (actionable fixes from architect - Phase 3 output)
#   - epic<N>-architect-fix-plan-done.md    (execution log - Phase 4 output)
#
# Usage: ./looper/code-review-analysis-fix.sh <epic-number> [phase] [--force]
#   phase: review, analyze, fix, architect, arch-fix, ci, git, or all (default: all)
#   --force: Skip architect review gate (not recommended)
#
# Recommended Workflow:
#   0. Run 'review' phase to execute both code review scripts (or run them manually)
#   1. Run 'analyze' phase to create fix plan + architect review needed
#   2. Run 'fix' phase to apply clear fixes immediately
#   3. Run 'architect' phase to get recommendations + fix plan for controversial items
#   4. Run 'arch-fix' phase to apply architect's fixes
#   5. Run 'ci' phase to run CI with auto-fix
#   6. Run 'git' phase to create local commit
#
# Examples:
#   ./looper/code-review-analysis-fix.sh 2              # Run all phases (including review)
#   ./looper/code-review-analysis-fix.sh 2 review       # Only run code review scripts
#   ./looper/code-review-analysis-fix.sh 2 analyze      # Only analyze (create plans)
#   ./looper/code-review-analysis-fix.sh 2 fix          # Only fix clear items
#   ./looper/code-review-analysis-fix.sh 2 architect    # Only get architect recommendations
#   ./looper/code-review-analysis-fix.sh 2 ci           # Only run CI
#   ./looper/code-review-analysis-fix.sh 2 git          # Only create commit
#   ./looper/code-review-analysis-fix.sh 2 all --force  # Run all, skip gates
#
# Stop: Ctrl+C (graceful shutdown)
#
# Prerequisites:
#   - Claude Code CLI installed
#   - Code review result files from both scripts
#

set -e
set -o pipefail

# Allow running from within a Claude Code session (e.g. via /bmad-dev)
unset CLAUDECODE 2>/dev/null || true

# =============================================================================
# Configuration
# =============================================================================
EPIC_NUMBER="${1:-}"
PHASE="${2:-}"   # empty = auto-resume from state file
FORCE_FIX="false"

# CI Configuration
MAX_CI_ATTEMPTS=4
CLAUDE_TIMEOUT_LONG="35m"  # For CI fix phases

# Parse --force flag from any position
for arg in "$@"; do
    if [[ "$arg" == "--force" ]]; then
        FORCE_FIX="true"
    fi
done

# Timezone: Central US (Austin, TX) via PowerShell (TZ env var unreliable on Windows)
get_timestamp() {
    powershell -Command "[System.TimeZoneInfo]::ConvertTimeBySystemTimeZoneId([DateTime]::UtcNow, 'Central Standard Time').ToString('yyyy-MM-dd HH:mm:ss')" 2>/dev/null || date '+%Y-%m-%d %H:%M:%S'
}

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT_DIR="$PROJECT_ROOT/_bmad-output"
IMPL_DIR="$OUTPUT_DIR/implementation-artifacts"
LOOPER_DIR="$PROJECT_ROOT/looper"

# Input files (from code-review-loop scripts)
BMAD_RESULTS_FILE="$LOOPER_DIR/epic${EPIC_NUMBER}-code-review-bmad-results.log"
CLAUDE_RESULTS_FILE="$LOOPER_DIR/epic${EPIC_NUMBER}-code-review-claude-results.log"

# Output files
LOG_FILE="$LOOPER_DIR/epic${EPIC_NUMBER}-code-review-analysis-fix.log"
ANALYSIS_FILE="$LOOPER_DIR/epic${EPIC_NUMBER}-code-review-analysis.md"
FIX_PLAN_FILE="$LOOPER_DIR/epic${EPIC_NUMBER}-code-review-fix-plan.md"
ARCHITECT_REVIEW_FILE="$LOOPER_DIR/epic${EPIC_NUMBER}-architect-review-needed.md"
ARCHITECT_RECOMMENDATIONS_FILE="$LOOPER_DIR/epic${EPIC_NUMBER}-architect-recommendations.md"
ARCHITECT_FIX_PLAN_FILE="$LOOPER_DIR/epic${EPIC_NUMBER}-architect-fix-plan.md"
ARCHITECT_FIX_PLAN_DONE_LOG="$LOOPER_DIR/epic${EPIC_NUMBER}-architect-fix-plan-done.md"
FIX_PLAN_DONE_LOG="$LOOPER_DIR/epic${EPIC_NUMBER}-code-review-fix-plan-done.md"
STATE_FILE="$LOOPER_DIR/epic${EPIC_NUMBER}-analysis-fix-state.json"

# =============================================================================
# SCOPED PERMISSIONS - Each phase gets only the tools it needs
# =============================================================================
# Phase 1: Analysis - needs read-only access plus writing analysis files
TOOLS_ANALYZE="Read,Glob,Grep,Write,Task,TodoWrite"

# Phase 3: Architect - needs read access to codebase + write for recommendations
TOOLS_ARCHITECT="Read,Glob,Grep,Write,Task,TodoWrite,WebSearch"

# Phase 2: Fix - needs full file editing plus testing
TOOLS_FIX="Read,Edit,Write,Glob,Grep,Task,TodoWrite,Bash(python *),Bash(pytest *),Bash(ruff *),Bash(mypy *),Bash(chmod *),Bash(git *)"

# Phase 5: CI Fix - needs file ops + linting tools
TOOLS_CI_FIX="Read,Edit,Write,Glob,Grep,Task,TodoWrite,Bash(python *),Bash(pip *),Bash(pytest *),Bash(ruff *),Bash(mypy *),Bash(chmod *),Bash(git *),Skill"

# =============================================================================
# Colors for output
# =============================================================================
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# =============================================================================
# Logging function
# =============================================================================
log() {
    local level="$1"
    local message="$2"
    local timestamp=$(get_timestamp)

    case "$level" in
        "INFO")    echo -e "${CYAN}${timestamp} [${level}] ${message}${NC}" ;;
        "WARN")    echo -e "${YELLOW}${timestamp} [${level}] ${message}${NC}" ;;
        "ERROR")   echo -e "${RED}${timestamp} [${level}] ${message}${NC}" ;;
        "SUCCESS") echo -e "${GREEN}${timestamp} [${level}] ${message}${NC}" ;;
        "PHASE")   echo -e "${MAGENTA}${timestamp} [${level}] ${message}${NC}" ;;
        *)         echo -e "${timestamp} [${level}] ${message}" ;;
    esac

    echo "${timestamp} [${level}] ${message}" >> "$LOG_FILE"
}

# =============================================================================
# Duration formatting function
# =============================================================================
format_duration() {
    local seconds="$1"
    if [[ $seconds -ge 60 ]]; then
        local mins=$((seconds / 60))
        local secs=$((seconds % 60))
        echo "${mins}m ${secs}s"
    else
        echo "${seconds}s"
    fi
}

# =============================================================================
# Output preview function
# =============================================================================
log_output_preview() {
    local phase="$1"
    local output="$2"
    local lines="${3:-10}"

    local preview=$(echo "$output" | head -n "$lines")

    echo ""
    echo -e "${CYAN}--- OUTPUT PREVIEW: $phase (first $lines lines) ---${NC}"
    echo "$preview"
    echo -e "${CYAN}--- END PREVIEW ---${NC}"
    echo ""
}

# =============================================================================
# State Management
# =============================================================================
save_state() {
    local phase="$1"
    local status="$2"

    cat > "$STATE_FILE" << EOF
{
    "epic": $EPIC_NUMBER,
    "phase": "$phase",
    "status": "$status",
    "timestamp": "$(get_timestamp)"
}
EOF
}

# =============================================================================
# Phase ordering and resume logic
# =============================================================================
# Ordered list of phases (index = execution order)
PHASE_ORDER=("review" "analyze" "fix" "architect" "arch-fix" "ci" "git")

phase_to_index() {
    local target="$1"
    for i in "${!PHASE_ORDER[@]}"; do
        if [[ "${PHASE_ORDER[$i]}" == "$target" ]]; then
            echo "$i"
            return
        fi
    done
    echo "-1"
}

# Read state file and resolve which phase to resume from.
# Returns the phase name to start at (via stdout).
resolve_resume_phase() {
    if [[ ! -f "$STATE_FILE" ]]; then
        echo "review"
        return
    fi

    # Parse JSON (simple — single-level flat structure)
    local last_phase last_status
    last_phase=$(grep '"phase"' "$STATE_FILE" | sed 's/.*: *"\([^"]*\)".*/\1/')
    last_status=$(grep '"status"' "$STATE_FILE" | sed 's/.*: *"\([^"]*\)".*/\1/')

    local idx
    idx=$(phase_to_index "$last_phase")
    if [[ "$idx" == "-1" ]]; then
        echo "review"
        return
    fi

    case "$last_status" in
        complete|skipped)
            # Completed or skipped — advance to next phase
            local next=$(( idx + 1 ))
            if [[ $next -ge ${#PHASE_ORDER[@]} ]]; then
                # All phases done — restart from review
                echo "review"
            else
                echo "${PHASE_ORDER[$next]}"
            fi
            ;;
        *)
            # in_progress, failed, or anything else — re-run this phase
            echo "$last_phase"
            ;;
    esac
}

# Global: the numeric index of the phase to start from (set in main)
START_PHASE_INDEX=0

# =============================================================================
# Graceful shutdown handler
# =============================================================================
# Global variables to track processes for cleanup
CLAUDE_PID=""
REVIEW_PIDS=""  # Space-separated PIDs for parallel review scripts

shutdown() {
    echo ""
    log "INFO" "Shutting down Analysis & Fix Loop..."

    # Kill any running parallel review scripts
    if [[ -n "$REVIEW_PIDS" ]]; then
        log "INFO" "Terminating review script processes: $REVIEW_PIDS"
        for pid in $REVIEW_PIDS; do
            kill -TERM "$pid" 2>/dev/null || true
        done
        sleep 1
        for pid in $REVIEW_PIDS; do
            kill -KILL "$pid" 2>/dev/null || true
        done
    fi

    # Kill any running Claude process
    if [[ -n "$CLAUDE_PID" ]]; then
        log "INFO" "Terminating Claude process (PID: $CLAUDE_PID)..."
        kill -TERM "$CLAUDE_PID" 2>/dev/null || true
        sleep 1
        kill -KILL "$CLAUDE_PID" 2>/dev/null || true
    fi

    # Clean up any temp files
    rm -f /tmp/claude_output_$$.txt /tmp/claude_prompt_$$.txt 2>/dev/null || true

    log "INFO" "State saved to: $STATE_FILE"
    log "INFO" "Log saved to: $LOG_FILE"
    exit 0
}

trap shutdown SIGINT SIGTERM

# =============================================================================
# Run Claude with proper signal handling
# =============================================================================
# This function runs Claude in its own process group so Ctrl+C works properly.
# Usage: run_claude_with_signal_handling "prompt" "allowed_tools" [timeout]
# Returns: Sets global CLAUDE_RESULT and CLAUDE_EXIT_CODE
#          Exit code 124 indicates timeout (matching standard timeout command)
CLAUDE_RESULT=""
CLAUDE_EXIT_CODE=0

run_claude_with_signal_handling() {
    local prompt="$1"
    local allowed_tools="$2"
    local timeout_duration="${3:-}"  # Optional timeout (e.g., "35m")

    local output_file="/tmp/claude_output_$$.txt"
    local prompt_file="/tmp/claude_prompt_$$.txt"

    # Clean up any previous temp files
    rm -f "$output_file" "$prompt_file" 2>/dev/null || true

    # Write prompt to temp file to avoid shell escaping issues
    printf '%s' "$prompt" > "$prompt_file"

    # Run Claude in background (no setsid — not available on Windows/MINGW)
    bash -c '
        exec claude --print --allowedTools "'"$allowed_tools"'" -- "$(cat "'"$prompt_file"'")"
    ' </dev/null >"$output_file" 2>&1 &
    CLAUDE_PID=$!

    # Wait for the process to complete, with optional timeout
    if [[ -n "$timeout_duration" ]]; then
        # Manual timeout: poll in a loop
        local timeout_secs=0
        # Parse timeout duration (supports "35m" or "300" seconds)
        if [[ "$timeout_duration" =~ ^([0-9]+)m$ ]]; then
            timeout_secs=$(( ${BASH_REMATCH[1]} * 60 ))
        elif [[ "$timeout_duration" =~ ^[0-9]+$ ]]; then
            timeout_secs=$timeout_duration
        else
            timeout_secs=2100  # Default 35 min
        fi

        local elapsed=0
        while kill -0 $CLAUDE_PID 2>/dev/null; do
            sleep 5
            elapsed=$((elapsed + 5))
            if [[ $elapsed -ge $timeout_secs ]]; then
                log "WARN" "Claude timed out after $timeout_duration - terminating..."
                kill -TERM $CLAUDE_PID 2>/dev/null || true
                sleep 2
                kill -KILL $CLAUDE_PID 2>/dev/null || true
                CLAUDE_EXIT_CODE=124
                CLAUDE_RESULT=$(cat "$output_file" 2>/dev/null || echo "")
                rm -f "$output_file" "$prompt_file" 2>/dev/null || true
                CLAUDE_PID=""
                return $CLAUDE_EXIT_CODE
            fi
        done
        wait $CLAUDE_PID 2>/dev/null
        CLAUDE_EXIT_CODE=$?
    else
        wait $CLAUDE_PID 2>/dev/null
        CLAUDE_EXIT_CODE=$?
    fi

    # Read the output
    CLAUDE_RESULT=$(cat "$output_file" 2>/dev/null || echo "")

    # Clean up
    rm -f "$output_file" "$prompt_file" 2>/dev/null || true
    CLAUDE_PID=""

    return $CLAUDE_EXIT_CODE
}

# =============================================================================
# Check if required input files exist
# =============================================================================
check_input_files() {
    local missing=0

    if [[ ! -f "$BMAD_RESULTS_FILE" ]]; then
        log "ERROR" "BMAD results file not found: $BMAD_RESULTS_FILE"
        log "INFO" "Run: ./looper/code-review-loop-bmad.sh $EPIC_NUMBER"
        missing=1
    else
        log "INFO" "Found BMAD results: $BMAD_RESULTS_FILE"
    fi

    if [[ ! -f "$CLAUDE_RESULTS_FILE" ]]; then
        log "ERROR" "Claude results file not found: $CLAUDE_RESULTS_FILE"
        log "INFO" "Run: ./looper/code-review-loop-claude.sh $EPIC_NUMBER"
        missing=1
    else
        log "INFO" "Found Claude results: $CLAUDE_RESULTS_FILE"
    fi

    return $missing
}

# =============================================================================
# PHASE 0: Run Both Code Review Scripts
# =============================================================================
run_review_phase() {
    local phase_start=$(date +%s)

    echo ""
    echo -e "${MAGENTA}============================================================${NC}"
    log "PHASE" "PHASE 0: RUN CODE REVIEW SCRIPTS"
    echo -e "${MAGENTA}============================================================${NC}"
    echo ""

    # Check which result files already exist
    local need_bmad=true
    local need_claude=true

    if [[ -f "$BMAD_RESULTS_FILE" ]]; then
        if [[ "$FORCE_FIX" == "true" ]]; then
            log "WARN" "--force specified, re-running BMAD review despite existing results"
        else
            log "INFO" "BMAD results already exist — skipping: $BMAD_RESULTS_FILE"
            need_bmad=false
        fi
    fi

    if [[ -f "$CLAUDE_RESULTS_FILE" ]]; then
        if [[ "$FORCE_FIX" == "true" ]]; then
            log "WARN" "--force specified, re-running Claude review despite existing results"
        else
            log "INFO" "Claude results already exist — skipping: $CLAUDE_RESULTS_FILE"
            need_claude=false
        fi
    fi

    # If both exist and not forcing, skip entire phase
    if [[ "$need_bmad" == "false" && "$need_claude" == "false" ]]; then
        log "INFO" "Both review result files already exist — skipping review phase"
        log "INFO" "  (Delete result files to force re-review, or use --force)"
        save_state "review" "complete"
        return 0
    fi

    save_state "review" "in_progress"

    local bmad_script="$LOOPER_DIR/code-review-loop-bmad.sh"
    local claude_script="$LOOPER_DIR/code-review-loop-claude.sh"

    # Verify needed scripts exist before launching anything
    if [[ "$need_bmad" == "true" && ! -f "$bmad_script" ]]; then
        log "ERROR" "BMAD review script not found: $bmad_script"
        return 1
    fi
    if [[ "$need_claude" == "true" && ! -f "$claude_script" ]]; then
        log "ERROR" "Claude review script not found: $claude_script"
        return 1
    fi
    [[ "$need_bmad" == "true" ]] && chmod +x "$bmad_script" 2>/dev/null || true
    [[ "$need_claude" == "true" ]] && chmod +x "$claude_script" 2>/dev/null || true

    if [[ "$need_bmad" == "true" && "$need_claude" == "true" ]]; then
        # ---- PARALLEL: Both reviews needed ----
        log "INFO" "Running BOTH review scripts in parallel..."
        log "INFO" "  BMAD script:   $bmad_script"
        log "INFO" "  Claude script: $claude_script"
        log "INFO" "  Epic: $EPIC_NUMBER"
        echo ""

        local parallel_start=$(date +%s)

        "$bmad_script" "$EPIC_NUMBER" &
        local bmad_pid=$!

        "$claude_script" "$EPIC_NUMBER" &
        local claude_pid=$!

        REVIEW_PIDS="$bmad_pid $claude_pid"

        log "INFO" "BMAD review launched  (PID: $bmad_pid)"
        log "INFO" "Claude review launched (PID: $claude_pid)"
        log "INFO" "Waiting for both reviews to complete..."

        local bmad_exit=0
        local claude_exit=0
        wait "$bmad_pid" || bmad_exit=$?
        wait "$claude_pid" || claude_exit=$?

        REVIEW_PIDS=""

        local parallel_duration=$(format_duration $(($(date +%s) - parallel_start)))

        if [[ $bmad_exit -ne 0 ]]; then
            log "ERROR" "BMAD review script failed (exit code: $bmad_exit)"
        elif [[ ! -f "$BMAD_RESULTS_FILE" ]]; then
            log "ERROR" "BMAD results file was not created: $BMAD_RESULTS_FILE"
            bmad_exit=1
        else
            log "SUCCESS" "BMAD review complete"
        fi

        if [[ $claude_exit -ne 0 ]]; then
            log "ERROR" "Claude review script failed (exit code: $claude_exit)"
        elif [[ ! -f "$CLAUDE_RESULTS_FILE" ]]; then
            log "ERROR" "Claude results file was not created: $CLAUDE_RESULTS_FILE"
            claude_exit=1
        else
            log "SUCCESS" "Claude review complete"
        fi

        log "INFO" "Parallel review duration: $parallel_duration"

        if [[ $bmad_exit -ne 0 || $claude_exit -ne 0 ]]; then
            save_state "review" "failed"
            return 1
        fi

    elif [[ "$need_bmad" == "true" ]]; then
        log "INFO" "Running BMAD code review script..."
        local bmad_exit_code=0
        if "$bmad_script" "$EPIC_NUMBER"; then
            log "SUCCESS" "BMAD review complete"
        else
            bmad_exit_code=$?
            log "ERROR" "BMAD review script failed (exit code: $bmad_exit_code)"
            save_state "review" "failed_bmad"
            return 1
        fi
    else
        log "INFO" "Running Claude code review script..."
        local claude_exit_code=0
        if "$claude_script" "$EPIC_NUMBER"; then
            log "SUCCESS" "Claude review complete"
        else
            claude_exit_code=$?
            log "ERROR" "Claude review script failed (exit code: $claude_exit_code)"
            save_state "review" "failed_claude"
            return 1
        fi
    fi

    local phase_duration=$(format_duration $(($(date +%s) - phase_start)))
    log "SUCCESS" "Phase 0 (Review) complete - Duration: $phase_duration"
    save_state "review" "complete"

    return 0
}

# =============================================================================
# PHASE 1: Analyze and Compare Code Review Results
# =============================================================================
run_analysis_phase() {
    local phase_start=$(date +%s)

    echo ""
    echo -e "${MAGENTA}============================================================${NC}"
    log "PHASE" "PHASE 1: ANALYZE CODE REVIEW RESULTS"
    echo -e "${MAGENTA}============================================================${NC}"
    echo ""

    save_state "analyze" "in_progress"

    if ! check_input_files; then
        log "ERROR" "Missing required input files. Run code review scripts first."
        return 1
    fi

    log "INFO" "Analyzing and comparing code review results..."
    log "INFO" "  Allowed tools: $TOOLS_ANALYZE"

    local prompt="You are analyzing code review results from two different review agents for Epic $EPIC_NUMBER.

TASK: Compare and analyze the code review findings from both agents, then create:
1. A fix plan with ONLY clear, non-controversial fixes
2. An architect review file with ONLY controversial/architectural items

CRITICAL: Items must go to ONE place only - NO OVERLAP between fix plan and architect review.

INPUT FILES TO READ:
1. BMAD Agent Results: $BMAD_RESULTS_FILE
2. Claude Direct Results: $CLAUDE_RESULTS_FILE
3. Project Coding Rules: $PROJECT_ROOT/CLAUDE.md
4. Coding Standards: $PROJECT_ROOT/coding-standards.md

## ISSUE CLASSIFICATION RULES

### Category A: CLEAR FIXES (go to Fix Plan ONLY)
- The fix is obvious and unambiguous
- No architectural decision is needed
- Examples: typos, missing imports, wrong paths, test assertion fixes, lint violations

### Category B: ARCHITECT REVIEW (go to Architect Review ONLY)
- Multiple valid approaches exist
- Security implications need expert review
- API contract changes are involved
- The fix could affect other epics/stories
- Examples: agent communication strategy, state management decisions, tool permission scope

IMPORTANT: If you're unsure which category, put it in Category B.

## REQUIRED OUTPUTS

### Output 1: Analysis File ($ANALYSIS_FILE)
Detailed analysis with: executive summary, agent coverage table, issue comparison, unique findings, consolidated issue list with A/B classification.

### Output 2: Fix Plan File ($FIX_PLAN_FILE)
ONLY Category A issues. Structured by priority (P0-P3) with file path, line number, issue description, specific fix action, and verification method.

### Output 3: Architect Review File ($ARCHITECT_REVIEW_FILE)
ONLY Category B issues. Each item needs: file paths, current state, why it needs architect review, options table, recommendation, and specific decision question.

Begin by reading the input files now."

    local timestamp=$(get_timestamp)
    cat >> "$LOG_FILE" << EOF

================================================================================
PROMPT: Phase 1 Analysis | Time: $timestamp
================================================================================
$prompt
================================================================================

EOF

    echo -e "${YELLOW}>>> Invoking Claude for analysis...${NC}"
    echo -e "${CYAN}    (Press Ctrl+C to stop gracefully)${NC}"
    run_claude_with_signal_handling "$prompt" "$TOOLS_ANALYZE"
    local result="$CLAUDE_RESULT"
    local exit_code=$CLAUDE_EXIT_CODE

    cat >> "$LOG_FILE" << EOF

================================================================================
OUTPUT: Phase 1 Analysis
================================================================================
$result
================================================================================

EOF

    log_output_preview "Phase 1 Analysis" "$result" 15

    if [[ $exit_code -ne 0 ]]; then
        log "ERROR" "Analysis phase failed (exit code: $exit_code)"
        save_state "analyze" "failed"
        return 1
    fi

    # Verify output files were created
    if [[ -f "$ANALYSIS_FILE" ]]; then
        log "SUCCESS" "Analysis file created: $ANALYSIS_FILE"
    else
        log "WARN" "Analysis file was not created: $ANALYSIS_FILE"
    fi

    if [[ -f "$FIX_PLAN_FILE" ]]; then
        log "SUCCESS" "Fix plan created: $FIX_PLAN_FILE"
    else
        log "WARN" "Fix plan file was not created: $FIX_PLAN_FILE"
    fi

    if [[ -f "$ARCHITECT_REVIEW_FILE" ]]; then
        local arch_items
        arch_items=$(grep -cE "^### [0-9]+\." "$ARCHITECT_REVIEW_FILE" 2>/dev/null) || arch_items=0
        if [[ $arch_items -gt 0 ]]; then
            log "SUCCESS" "Architect review created: $ARCHITECT_REVIEW_FILE ($arch_items items)"
        fi
    fi

    local phase_duration=$(format_duration $(($(date +%s) - phase_start)))
    log "SUCCESS" "Phase 1 (Analysis) complete - Duration: $phase_duration"
    save_state "analyze" "complete"

    return 0
}

# =============================================================================
# Check for Architect Review Gate
# =============================================================================
check_architect_review_gate() {
    if [[ ! -f "$ARCHITECT_REVIEW_FILE" ]]; then
        return 0
    fi

    local review_count
    review_count=$(grep -cE "^### [0-9]+\." "$ARCHITECT_REVIEW_FILE" 2>/dev/null) || review_count=0

    if [[ $review_count -eq 0 ]]; then
        return 0
    fi

    echo ""
    log "WARN" "Found $review_count items requiring architect review"
    log "INFO" "Architect review file: $ARCHITECT_REVIEW_FILE"

    if [[ "${FORCE_FIX:-false}" == "true" ]]; then
        log "WARN" "FORCE_FIX=true - Continuing without architect review"
        return 0
    fi

    read -p "Continue without architect review? [y/N]: " choice
    case "$choice" in
        y|Y) log "WARN" "Continuing - architect items will be skipped"; return 0 ;;
        *)   log "INFO" "Review: $ARCHITECT_REVIEW_FILE then run: $0 $EPIC_NUMBER fix"; exit 0 ;;
    esac
}

# =============================================================================
# PHASE 2: Apply Fixes from the Plan
# =============================================================================
run_fix_phase() {
    local phase_start=$(date +%s)

    echo ""
    echo -e "${MAGENTA}============================================================${NC}"
    log "PHASE" "PHASE 2: APPLY CODE REVIEW FIXES"
    echo -e "${MAGENTA}============================================================${NC}"
    echo ""

    save_state "fix" "in_progress"

    if [[ ! -f "$FIX_PLAN_FILE" ]]; then
        log "ERROR" "Fix plan file not found: $FIX_PLAN_FILE"
        return 1
    fi

    log "INFO" "Applying fixes from: $FIX_PLAN_FILE"
    log "INFO" "Allowed tools: $TOOLS_FIX"

    sleep 10  # State reset delay

    local prompt="You are applying code review fixes for Epic $EPIC_NUMBER in the Shipyard project.

CRITICAL FIRST STEP: Read the project coding rules before making ANY changes:
- $PROJECT_ROOT/CLAUDE.md
- $PROJECT_ROOT/coding-standards.md

TASK: Apply the fixes from the fix plan file.

FIX PLAN FILE: $FIX_PLAN_FILE

EXECUTION LOGGING REQUIREMENT:
Before applying any fixes, create this log file:
  $FIX_PLAN_DONE_LOG

For EACH fix you apply, write an entry in this format:
  [YYYY-MM-DD HH:MM:SS FIX #N] path/to/file
    - Description of change made

If you skip a fix, log it as:
  [YYYY-MM-DD HH:MM:SS SKIPPED #N] Reason for skipping

End the log with a summary line:
  # Completed: X/Y fixes applied, Z skipped

INSTRUCTIONS:
1. Read CLAUDE.md and coding-standards.md FIRST
2. Read the fix plan file completely
3. Apply fixes in priority order (P0 first, then P1, P2, P3)
4. For each fix: read the file, apply the fix, verify it
5. After all fixes, run verification: pytest, ruff check

If you encounter ambiguity, SKIP that fix and log it as SKIPPED.

=== FIX SUMMARY ===
Total fixes applied: [count]
Fixes skipped: [count]
Files modified: [list]
Tests run: [pass/fail counts]
=== END SUMMARY ===

Begin by reading CLAUDE.md and the fix plan now."

    local timestamp=$(get_timestamp)
    cat >> "$LOG_FILE" << EOF

================================================================================
PROMPT: Phase 2 Fix | Time: $timestamp
================================================================================
$prompt
================================================================================

EOF

    echo -e "${YELLOW}>>> Invoking Dev Agent to apply fixes...${NC}"
    run_claude_with_signal_handling "$prompt" "$TOOLS_FIX"
    local result="$CLAUDE_RESULT"
    local exit_code=$CLAUDE_EXIT_CODE

    cat >> "$LOG_FILE" << EOF

================================================================================
OUTPUT: Phase 2 Fix
================================================================================
$result
================================================================================

EOF

    log_output_preview "Phase 2 Fix" "$result" 20

    if [[ $exit_code -ne 0 ]]; then
        log "ERROR" "Fix phase failed (exit code: $exit_code)"
        save_state "fix" "failed"
        return 1
    fi

    if echo "$result" | grep -q "=== FIX SUMMARY ==="; then
        echo ""
        echo -e "${GREEN}=== FIX SUMMARY ===${NC}"
        echo "$result" | sed -n '/=== FIX SUMMARY ===/,/=== END SUMMARY ===/p'
        echo ""
    fi

    check_skipped_items

    local phase_duration=$(format_duration $(($(date +%s) - phase_start)))
    log "SUCCESS" "Phase 2 (Fix) complete - Duration: $phase_duration"
    save_state "fix" "complete"

    return 0
}

# =============================================================================
# Check for Skipped Items and Append to Architect Review File
# =============================================================================
check_skipped_items() {
    if [[ ! -f "$FIX_PLAN_DONE_LOG" ]]; then
        return 0
    fi

    local skipped_count
    skipped_count=$(grep -cE "^\[.*SKIPPED #[0-9]+\]" "$FIX_PLAN_DONE_LOG" 2>/dev/null) || skipped_count=0

    if [[ $skipped_count -eq 0 ]]; then
        return 0
    fi

    log "WARN" "$skipped_count items were skipped during fix phase"
    log "INFO" "Appending skipped items to architect review file..."

    local existing_count=0
    if [[ -f "$ARCHITECT_REVIEW_FILE" ]]; then
        existing_count=$(grep -cE "^### [0-9]+\." "$ARCHITECT_REVIEW_FILE" 2>/dev/null) || existing_count=0
    else
        local timestamp=$(get_timestamp)
        cat > "$ARCHITECT_REVIEW_FILE" << EOF
# Epic $EPIC_NUMBER - Architect Review Required

**Generated:** $timestamp
**Source:** Code Review Analysis

---

## Items Requiring Architectural Decision

EOF
    fi

    local timestamp=$(get_timestamp)
    cat >> "$ARCHITECT_REVIEW_FILE" << EOF

---

## Items Skipped During Fix Phase

*Added: $timestamp*

EOF

    local item_num=$((existing_count + 1))
    grep -E "^\[.*SKIPPED #[0-9]+\]" "$FIX_PLAN_DONE_LOG" | while read -r line; do
        local skip_info=$(echo "$line" | sed 's/^\[.*SKIPPED #[0-9]*\] //')
        local skip_ref=$(echo "$line" | grep -oE "SKIPPED #[0-9]+")

        cat >> "$ARCHITECT_REVIEW_FILE" << EOF
### $item_num. $skip_ref
- **Source:** Fix phase execution
- **Reason:** $skip_info
- **Decision Required:** Determine the correct fix approach

EOF
        item_num=$((item_num + 1))
    done

    log "WARN" "Appended $skipped_count skipped items to: $ARCHITECT_REVIEW_FILE"
}

# =============================================================================
# PHASE 3: Architect Review and Recommendations
# =============================================================================
run_architect_phase() {
    local phase_start=$(date +%s)

    echo ""
    echo -e "${MAGENTA}============================================================${NC}"
    log "PHASE" "PHASE 3: ARCHITECT REVIEW AND RECOMMENDATIONS"
    echo -e "${MAGENTA}============================================================${NC}"
    echo ""

    save_state "architect" "in_progress"

    if [[ ! -f "$ARCHITECT_REVIEW_FILE" ]]; then
        log "INFO" "No architect review file found. Skipping."
        save_state "architect" "skipped"
        return 0
    fi

    local review_count
    review_count=$(grep -cE "^### [0-9]+\." "$ARCHITECT_REVIEW_FILE" 2>/dev/null) || review_count=0
    if [[ $review_count -eq 0 ]]; then
        log "INFO" "No items requiring architect review."
        save_state "architect" "skipped"
        return 0
    fi

    log "INFO" "Reviewing $review_count items requiring architectural decisions"

    sleep 10  # State reset delay

    local prompt="You are the System Architect reviewing controversial code review items for Epic $EPIC_NUMBER in the Shipyard project.

INPUT FILES TO READ:
1. Architect Review File: $ARCHITECT_REVIEW_FILE
2. Project Coding Rules: $PROJECT_ROOT/CLAUDE.md
3. Coding Standards: $PROJECT_ROOT/coding-standards.md
4. Architecture: $PROJECT_ROOT/_bmad-output/planning-artifacts/architecture.md

YOUR TASK:
1. Analyze each controversial item
2. Make a clear decision with rationale
3. Create TWO output files:

OUTPUT FILE 1: $ARCHITECT_RECOMMENDATIONS_FILE
Recommendations document with: executive summary table, detailed rationale per item, implementation guidance.

OUTPUT FILE 2: $ARCHITECT_FIX_PLAN_FILE
Concrete fix plan that a dev agent can execute without judgment calls. Each fix needs: priority, exact file path, issue description, exact fix action, code examples, verification method.

GUIDELINES:
- Be decisive - pick ONE option for each item
- Reference coding-standards.md for consistency
- The fix plan must be specific enough for a dev agent to execute WITHOUT reading the recommendations
- Do NOT include items that require further decisions

Begin by reading the architect review file and CLAUDE.md now."

    local timestamp=$(get_timestamp)
    cat >> "$LOG_FILE" << EOF

================================================================================
PROMPT: Phase 3 Architect | Time: $timestamp
================================================================================
$prompt
================================================================================

EOF

    echo -e "${YELLOW}>>> Invoking Architect Agent...${NC}"
    run_claude_with_signal_handling "$prompt" "$TOOLS_ARCHITECT"
    local result="$CLAUDE_RESULT"
    local exit_code=$CLAUDE_EXIT_CODE

    cat >> "$LOG_FILE" << EOF

================================================================================
OUTPUT: Phase 3 Architect
================================================================================
$result
================================================================================

EOF

    log_output_preview "Phase 3 Architect" "$result" 20

    if [[ $exit_code -ne 0 ]]; then
        log "ERROR" "Architect phase failed (exit code: $exit_code)"
        save_state "architect" "failed"
        return 1
    fi

    [[ -f "$ARCHITECT_RECOMMENDATIONS_FILE" ]] && log "SUCCESS" "Recommendations: $ARCHITECT_RECOMMENDATIONS_FILE"
    [[ -f "$ARCHITECT_FIX_PLAN_FILE" ]] && log "SUCCESS" "Fix plan: $ARCHITECT_FIX_PLAN_FILE"

    local phase_duration=$(format_duration $(($(date +%s) - phase_start)))
    log "SUCCESS" "Phase 3 (Architect) complete - Duration: $phase_duration"
    save_state "architect" "complete"

    return 0
}

# =============================================================================
# PHASE 4: Apply Architect Fix Plan
# =============================================================================
run_arch_fix_phase() {
    local phase_start=$(date +%s)

    echo ""
    echo -e "${MAGENTA}============================================================${NC}"
    log "PHASE" "PHASE 4: APPLY ARCHITECT FIX PLAN"
    echo -e "${MAGENTA}============================================================${NC}"
    echo ""

    save_state "arch-fix" "in_progress"

    if [[ ! -f "$ARCHITECT_FIX_PLAN_FILE" ]]; then
        log "INFO" "No architect fix plan found — skipping (architect phase produced no fixes)."
        save_state "arch-fix" "skipped"
        return 0
    fi

    local fix_count
    fix_count=$(grep -cE "^### Fix [0-9]+" "$ARCHITECT_FIX_PLAN_FILE" 2>/dev/null) || fix_count=0
    if [[ $fix_count -eq 0 ]]; then
        log "INFO" "No fixes in architect fix plan."
        save_state "arch-fix" "skipped"
        return 0
    fi

    log "INFO" "Applying $fix_count fixes from architect fix plan"

    sleep 10  # State reset delay

    local prompt="You are applying fixes from the architect's fix plan for Epic $EPIC_NUMBER in the Shipyard project.

CRITICAL FIRST STEP: Read the project coding rules:
- $PROJECT_ROOT/CLAUDE.md
- $PROJECT_ROOT/coding-standards.md

TASK: Apply the fixes from the architect's fix plan.

FIX PLAN FILE: $ARCHITECT_FIX_PLAN_FILE

EXECUTION LOGGING REQUIREMENT:
Create log file: $ARCHITECT_FIX_PLAN_DONE_LOG

For EACH fix, log: [YYYY-MM-DD HH:MM:SS FIX #N] path/to/file - Description
For SKIPPED: [YYYY-MM-DD HH:MM:SS SKIPPED #N] Reason

IMPORTANT: The architect has already made all decisions. Your job is to execute, not to decide.

After all fixes, run verification: pytest, ruff check

=== ARCHITECT FIX SUMMARY ===
Total fixes applied: [count]
Fixes skipped: [count]
Files modified: [list]
=== END SUMMARY ===

Begin by reading CLAUDE.md and the architect fix plan now."

    local timestamp=$(get_timestamp)
    cat >> "$LOG_FILE" << EOF

================================================================================
PROMPT: Phase 4 Arch-Fix | Time: $timestamp
================================================================================
$prompt
================================================================================

EOF

    echo -e "${YELLOW}>>> Invoking Dev Agent to apply architect fixes...${NC}"
    run_claude_with_signal_handling "$prompt" "$TOOLS_FIX"
    local result="$CLAUDE_RESULT"
    local exit_code=$CLAUDE_EXIT_CODE

    cat >> "$LOG_FILE" << EOF

================================================================================
OUTPUT: Phase 4 Arch-Fix
================================================================================
$result
================================================================================

EOF

    log_output_preview "Phase 4 Arch-Fix" "$result" 20

    if [[ $exit_code -ne 0 ]]; then
        log "ERROR" "Arch-fix phase failed (exit code: $exit_code)"
        save_state "arch-fix" "failed"
        return 1
    fi

    local phase_duration=$(format_duration $(($(date +%s) - phase_start)))
    log "SUCCESS" "Phase 4 (Arch-Fix) complete - Duration: $phase_duration"
    save_state "arch-fix" "complete"

    return 0
}

# =============================================================================
# PHASE 5: Run CI Pipeline with Retry Loop
# =============================================================================
run_ci_phase() {
    local phase_start=$(date +%s)

    echo ""
    echo -e "${MAGENTA}============================================================${NC}"
    log "PHASE" "PHASE 5: CI PIPELINE"
    echo -e "${MAGENTA}============================================================${NC}"
    echo ""

    save_state "ci" "in_progress"

    local ci_script="$PROJECT_ROOT/scripts/local_ci.sh"

    if [[ ! -f "$ci_script" ]]; then
        log "ERROR" "CI script not found: $ci_script"
        return 1
    fi

    chmod +x "$ci_script" 2>/dev/null || true

    log "INFO" "Running local CI pipeline ($ci_script)"
    log "INFO" "Max attempts: $MAX_CI_ATTEMPTS"

    cd "$PROJECT_ROOT"

    local ci_passed=false
    local ci_attempt=0
    local ci_timeout_retries=0
    local max_ci_timeout_retries=1

    while [[ $ci_attempt -lt $MAX_CI_ATTEMPTS && "$ci_passed" != "true" ]]; do
        ((ci_attempt++))
        save_state "ci" "attempt_$ci_attempt"
        log "INFO" "CI attempt $ci_attempt of $MAX_CI_ATTEMPTS"

        local ci_result=""
        local ci_exit_code=0

        ci_result=$("$ci_script" 2>&1) || ci_exit_code=$?

        echo "$ci_result" >> "$LOG_FILE"

        if [[ $ci_exit_code -eq 0 ]]; then
            ci_passed=true
            local phase_duration=$(format_duration $(($(date +%s) - phase_start)))
            log "SUCCESS" "CI passed! ($phase_duration)"
        else
            log "WARN" "CI failed (exit code: $ci_exit_code), asking Claude to fix..."

            echo ""
            echo -e "${RED}=== CI FAILURE SUMMARY ===${NC}"

            # Extract test failures
            local test_failures=$(echo "$ci_result" | grep -E "^FAILED " | head -10)
            if [[ -n "$test_failures" ]]; then
                echo -e "${YELLOW}Test Failures:${NC}"
                echo "$test_failures"
                echo ""
            fi

            # Extract lint errors
            local ruff_errors=$(echo "$ci_result" | grep -E "^(src|tests)/.*:[0-9]+:[0-9]+:" | head -10)
            if [[ -n "$ruff_errors" ]]; then
                echo -e "${YELLOW}Lint Errors (ruff):${NC}"
                echo "$ruff_errors"
                echo ""
            fi

            # Extract type errors
            local mypy_errors=$(echo "$ci_result" | grep -E "^(src|tests)/.*: error:" | head -10)
            if [[ -n "$mypy_errors" ]]; then
                echo -e "${YELLOW}Type Errors (mypy):${NC}"
                echo "$mypy_errors"
                echo ""
            fi

            echo -e "${RED}=== END FAILURE SUMMARY ===${NC}"
            echo ""

            local ci_issues_file="$LOOPER_DIR/epic${EPIC_NUMBER}-ci-issues-attempt-${ci_attempt}.txt"
            echo "$ci_result" > "$ci_issues_file"

            local fix_prompt="Fix CI failures for Epic $EPIC_NUMBER in the Shipyard project.

CRITICAL FIRST STEP: Read $PROJECT_ROOT/CLAUDE.md and $PROJECT_ROOT/coding-standards.md for coding rules.

CI ISSUES FILE: $ci_issues_file

Fix all lint errors (ruff), type errors (mypy), and test failures (pytest).

After fixing, output:
=== CI FIXES APPLIED ===
- [LINT/TEST/TYPE] Brief description (file:line)
=== END CI FIXES ===

Begin by reading CLAUDE.md and the CI issues file now."

            local timestamp=$(get_timestamp)
            cat >> "$LOG_FILE" << EOF

================================================================================
PROMPT: Phase 5 CI Fix | Attempt $ci_attempt | Time: $timestamp
================================================================================
$fix_prompt
================================================================================

EOF

            log "INFO" "Pausing 15 seconds before CI fix..."
            sleep 15

            echo -e "${YELLOW}>>> Invoking Dev Agent to fix CI issues...${NC}"

            run_claude_with_signal_handling "$fix_prompt" "$TOOLS_CI_FIX" "$CLAUDE_TIMEOUT_LONG"
            local fix_result="$CLAUDE_RESULT"
            local fix_exit_code=$CLAUDE_EXIT_CODE

            cat >> "$LOG_FILE" << EOF

================================================================================
OUTPUT: Phase 5 CI Fix | Attempt $ci_attempt
================================================================================
$fix_result
================================================================================

EOF

            log_output_preview "CI Fix Attempt $ci_attempt" "$fix_result" 15

            # Handle timeout
            if [[ $fix_exit_code -eq 124 ]]; then
                ((ci_timeout_retries++))
                log "WARN" "CI fix timed out after $CLAUDE_TIMEOUT_LONG"
                if [[ $ci_timeout_retries -le $max_ci_timeout_retries ]]; then
                    ((ci_attempt--))
                    sleep 30
                    continue
                else
                    log "ERROR" "CI fix timed out twice - stopping"
                    save_state "ci" "timeout_failed"
                    return 1
                fi
            fi
        fi
    done

    # Verification run if needed
    if [[ "$ci_passed" != "true" && $ci_attempt -eq $MAX_CI_ATTEMPTS ]]; then
        log "INFO" "Running verification CI after final fix attempt..."
        ci_exit_code=0
        ci_result=$("$ci_script" 2>&1) || ci_exit_code=$?
        if [[ $ci_exit_code -eq 0 ]]; then
            ci_passed=true
            log "SUCCESS" "CI passed on verification run!"
        fi
    fi

    if [[ "$ci_passed" != "true" ]]; then
        local phase_duration=$(format_duration $(($(date +%s) - phase_start)))
        log "ERROR" "CI failed after $MAX_CI_ATTEMPTS attempts ($phase_duration)"
        save_state "ci" "failed"
        return 1
    fi

    local phase_duration=$(format_duration $(($(date +%s) - phase_start)))
    log "SUCCESS" "Phase 5 (CI) complete - Duration: $phase_duration"
    save_state "ci" "complete"

    return 0
}

# =============================================================================
# Git Commit with Pre-commit Hook Retry Logic
# =============================================================================
git_commit_changes() {
    local commit_msg="$1"
    local max_retries=3
    local retry_count=0

    cd "$PROJECT_ROOT"

    # Pre-commit: basic ruff check
    log "INFO" "Running pre-commit ruff check..."
    if command -v ruff &> /dev/null; then
        ruff check "$PROJECT_ROOT/src" "$PROJECT_ROOT/tests" --select=E,F --ignore=E501 --fix --quiet 2>&1 || true
    fi

    while [[ $retry_count -lt $max_retries ]]; do
        git add .

        local has_changes=$(git status --porcelain)
        if [[ -z "$has_changes" ]]; then
            log "INFO" "No changes to commit"
            return 0
        fi

        local commit_output
        local exit_code=0

        commit_output=$(git commit -m "$commit_msg" 2>&1) || exit_code=$?

        if [[ $retry_count -eq 0 ]]; then
            echo "$commit_output" | tee -a "$LOG_FILE"
        else
            echo "$commit_output" >> "$LOG_FILE"
        fi

        if [[ $exit_code -eq 0 ]]; then
            if [[ $retry_count -gt 0 ]]; then
                log "SUCCESS" "Commit succeeded after pre-commit auto-fixes (attempt $((retry_count + 1)))"
            else
                log "SUCCESS" "Created commit: $commit_msg"
            fi
            return 0
        fi

        # Check if pre-commit hooks modified files
        if echo "$commit_output" | grep -qE "(files were modified by this hook|reformatted|Fixing )"; then
            ((retry_count++))
            log "INFO" "Pre-commit hooks modified files, re-staging (attempt $retry_count)..."
            sleep 1
            continue
        fi

        log "ERROR" "Failed to create commit (non-recoverable error)"
        echo "$commit_output" | tail -30
        return 1
    done

    log "ERROR" "Failed to create commit after $max_retries retries"
    return 1
}

# =============================================================================
# PHASE 6: Git Commit
# =============================================================================
run_git_phase() {
    local phase_start=$(date +%s)

    echo ""
    echo -e "${MAGENTA}============================================================${NC}"
    log "PHASE" "PHASE 6: GIT COMMIT"
    echo -e "${MAGENTA}============================================================${NC}"
    echo ""

    save_state "git" "in_progress"

    cd "$PROJECT_ROOT"

    local has_changes=$(git status --porcelain)
    if [[ -z "$has_changes" ]]; then
        log "INFO" "No changes to commit"
        save_state "git" "skipped"
        return 0
    fi

    log "INFO" "Changes detected - creating commit..."
    git status --short | head -20

    local commit_msg="epic ${EPIC_NUMBER} code review fixes

Applied automated code review fixes from analysis phase.

Co-Authored-By: Claude Opus 4.6 <noreply@anthropic.com>"

    if git_commit_changes "$commit_msg"; then
        local phase_duration=$(format_duration $(($(date +%s) - phase_start)))
        log "SUCCESS" "Phase 6 (Git Commit) complete - Duration: $phase_duration"
        save_state "git" "complete"
        echo ""
        log "INFO" "Latest commit:"
        git log --oneline -1
        echo ""
        return 0
    else
        log "ERROR" "Failed to create commit"
        save_state "git" "failed"
        return 1
    fi
}

# =============================================================================
# Check Dependencies — install missing Python packages automatically
# =============================================================================
check_dependencies() {
    local missing=false

    # --- Required system commands ---
    if ! command -v claude &> /dev/null; then
        log "ERROR" "Claude CLI not found. Install: npm install -g @anthropic-ai/claude-code"
        missing=true
    else
        log "INFO" "claude: $(claude --version 2>&1 | head -1)"
    fi

    if ! command -v git &> /dev/null; then
        log "ERROR" "git not found. Install git first."
        missing=true
    else
        log "INFO" "git: $(git --version 2>&1)"
    fi

    if ! command -v python &> /dev/null; then
        log "ERROR" "python not found. Install Python 3.13+."
        missing=true
    else
        log "INFO" "python: $(python --version 2>&1)"
    fi

    if [[ "$missing" == "true" ]]; then
        log "ERROR" "Missing required system dependencies — cannot continue."
        exit 1
    fi

    # --- Required Python packages (auto-install from requirements-dev.txt) ---
    local py_packages=("ruff" "mypy" "pytest")
    local need_install=false

    for pkg in "${py_packages[@]}"; do
        if ! python -m "$pkg" --version &> /dev/null; then
            log "WARN" "$pkg not found in Python environment."
            need_install=true
        else
            log "INFO" "$pkg: $(python -m "$pkg" --version 2>&1 | head -1)"
        fi
    done

    if [[ "$need_install" == "true" ]]; then
        local req_file="$PROJECT_ROOT/requirements-dev.txt"
        if [[ -f "$req_file" ]]; then
            log "INFO" "Installing missing Python packages from requirements-dev.txt..."
            if python -m pip install -r "$req_file" --quiet 2>&1; then
                log "SUCCESS" "Python packages installed successfully."
                # Verify after install
                for pkg in "${py_packages[@]}"; do
                    if ! python -m "$pkg" --version &> /dev/null; then
                        log "ERROR" "$pkg still not available after install."
                        missing=true
                    else
                        log "INFO" "$pkg: $(python -m "$pkg" --version 2>&1 | head -1)"
                    fi
                done
            else
                log "ERROR" "pip install failed. Run manually: pip install -r $req_file"
                missing=true
            fi
        else
            log "ERROR" "requirements-dev.txt not found at $req_file — install ruff, mypy, pytest manually."
            missing=true
        fi
    fi

    if [[ "$missing" == "true" ]]; then
        log "ERROR" "Missing Python dependencies — cannot continue."
        exit 1
    fi
}

# =============================================================================
# Main Entry Point
# =============================================================================
main() {
    echo ""
    echo -e "  ${MAGENTA}=====================================${NC}"
    echo -e "  ${MAGENTA}CODE REVIEW ANALYSIS & FIX${NC}"
    echo -e "  ${MAGENTA}Shipyard Automated Code Quality${NC}"
    echo -e "  ${MAGENTA}=====================================${NC}"
    echo ""

    if [[ -z "$EPIC_NUMBER" ]]; then
        echo "Usage: $0 <epic-number> [phase] [--force]"
        echo ""
        echo "Phases:"
        echo "  (none)    - Auto-resume from state file, or run all if no state"
        echo "  review    - Run both code review scripts (BMAD + Claude)"
        echo "  analyze   - Create fix plan (clear fixes) + architect review (controversial)"
        echo "  fix       - Apply clear, non-controversial fixes"
        echo "  architect - Generate architect recommendations + fix plan"
        echo "  arch-fix  - Apply fixes from the architect's fix plan"
        echo "  ci        - Run CI pipeline with auto-fix retry loop"
        echo "  git       - Create local git commit"
        echo "  all       - Run all seven phases from the beginning"
        echo ""
        echo "Options:"
        echo "  --force - Skip architect review gate"
        echo ""
        echo "Examples:"
        echo "  $0 2              # Auto-resume from last state (or all if fresh)"
        echo "  $0 2 all          # Force run all phases from the start"
        echo "  $0 2 review       # Only run code review scripts"
        echo "  $0 2 analyze      # Only analyze"
        echo "  $0 2 fix          # Only fix clear items"
        echo "  $0 2 ci           # Only run CI"
        echo "  $0 2 git          # Only create commit"
        exit 1
    fi

    # Resolve phase: empty → auto-resume, explicit → validate
    if [[ -z "$PHASE" ]]; then
        PHASE="resume"
    fi

    case "$PHASE" in
        review|analyze|fix|architect|arch-fix|ci|git|all|resume) ;;
        *) echo -e "${RED}Error: Invalid phase '$PHASE'${NC}"; exit 1 ;;
    esac

    # Resolve run mode:
    #   resume / empty → read state file, run from that phase through the end
    #   all            → run all phases from the beginning
    #   <specific>     → run only that one phase (original behavior)
    ORIGINAL_PHASE="$PHASE"
    if [[ "$PHASE" == "resume" ]]; then
        local resume_from
        resume_from=$(resolve_resume_phase)
        log "INFO" "Resuming from state file → starting at phase: $resume_from"
        START_PHASE_INDEX=$(phase_to_index "$resume_from")
    elif [[ "$PHASE" == "all" ]]; then
        START_PHASE_INDEX=0
    else
        # Single-phase mode: only run that one phase
        START_PHASE_INDEX=-1  # sentinel
    fi

    local phase_label
    if [[ $START_PHASE_INDEX -ge 0 ]]; then
        phase_label="${PHASE_ORDER[$START_PHASE_INDEX]} → git"
    else
        phase_label="$PHASE (single)"
    fi

    cat > "$LOG_FILE" << EOF
================================================================================
CODE REVIEW ANALYSIS & FIX LOG
Epic: $EPIC_NUMBER
Phase: $phase_label
Started: $(get_timestamp)
================================================================================

EOF

    check_dependencies

    log "INFO" "Starting Code Review Analysis & Fix - Epic $EPIC_NUMBER, phases: $phase_label"
    echo ""

    local total_start=$(date +%s)

    # Helper: should this phase run?
    #   Multi-phase mode (START_PHASE_INDEX >= 0): run if index >= start
    #   Single-phase mode (START_PHASE_INDEX == -1): run if name matches ORIGINAL_PHASE
    should_run() {
        local phase_name="$1"
        if [[ $START_PHASE_INDEX -ge 0 ]]; then
            local idx
            idx=$(phase_to_index "$phase_name")
            [[ $idx -ge $START_PHASE_INDEX ]]
        else
            [[ "$phase_name" == "$ORIGINAL_PHASE" ]]
        fi
    }

    # Track results for phases that actually ran
    declare -A phase_result  # "true", "false", or unset (not run)
    local failed=false
    local sleep_between=15   # seconds between phases in multi-phase mode
    local multi_phase=$(( START_PHASE_INDEX >= 0 ? 1 : 0 ))

    # Phase 0: Review
    if should_run "review"; then
        if run_review_phase; then
            phase_result[review]=true
        else
            phase_result[review]=false
            failed=true
            [[ $multi_phase -eq 1 ]] && { log "ERROR" "Review failed — stopping pipeline."; }
        fi
        [[ $multi_phase -eq 1 && "$failed" == "false" ]] && sleep 30
    fi

    # Phase 1: Analysis
    if should_run "analyze" && [[ "$failed" == "false" || $multi_phase -eq 0 ]]; then
        if run_analysis_phase; then
            phase_result[analyze]=true
        else
            phase_result[analyze]=false
            failed=true
        fi
        [[ $multi_phase -eq 1 && "$failed" == "false" ]] && sleep $sleep_between
    fi

    # Phase 2: Fix
    if should_run "fix" && [[ "$failed" == "false" || $multi_phase -eq 0 ]]; then
        [[ $multi_phase -eq 0 ]] && { check_architect_review_gate || true; }
        if run_fix_phase; then
            phase_result[fix]=true
        else
            phase_result[fix]=false
            # Fix failure is non-fatal for the pipeline — architect + CI can still run
        fi
        [[ $multi_phase -eq 1 ]] && sleep $sleep_between
    fi

    # Phase 3: Architect
    if should_run "architect" && [[ "$failed" == "false" || $multi_phase -eq 0 ]]; then
        if run_architect_phase; then
            phase_result[architect]=true
        else
            phase_result[architect]=false
            failed=true
        fi
        [[ $multi_phase -eq 1 && "$failed" == "false" ]] && sleep $sleep_between
    fi

    # Phase 4: Arch-Fix
    if should_run "arch-fix" && [[ "$failed" == "false" || $multi_phase -eq 0 ]]; then
        if run_arch_fix_phase; then
            phase_result[arch-fix]=true
        else
            phase_result[arch-fix]=false
            failed=true
        fi
        [[ $multi_phase -eq 1 && "$failed" == "false" ]] && sleep $sleep_between
    fi

    # Phase 5: CI
    if should_run "ci" && [[ "$failed" == "false" || $multi_phase -eq 0 ]]; then
        if run_ci_phase; then
            phase_result[ci]=true
        else
            phase_result[ci]=false
            failed=true
        fi
        [[ $multi_phase -eq 1 && "$failed" == "false" ]] && sleep 5
    fi

    # Phase 6: Git
    if should_run "git" && [[ "$failed" == "false" || $multi_phase -eq 0 ]]; then
        if run_git_phase; then
            phase_result[git]=true
        else
            phase_result[git]=false
            failed=true
        fi
    fi

    # Final Summary — only report phases that were attempted
    local total_duration=$(format_duration $(($(date +%s) - total_start)))
    local phase_names=("review" "analyze" "fix" "architect" "arch-fix" "ci" "git")
    local phase_labels=("Phase 0 (Review)" "Phase 1 (Analysis)" "Phase 2 (Fix)" "Phase 3 (Architect)" "Phase 4 (Arch-Fix)" "Phase 5 (CI)" "Phase 6 (Git)")

    echo ""
    echo -e "${MAGENTA}============================================================${NC}"
    log "INFO" "CODE REVIEW ANALYSIS & FIX COMPLETE"
    echo -e "${MAGENTA}============================================================${NC}"
    log "INFO" "Epic: $EPIC_NUMBER | Duration: $total_duration"

    local any_failed=false
    for i in "${!phase_names[@]}"; do
        local pn="${phase_names[$i]}"
        local pl="${phase_labels[$i]}"
        if [[ -n "${phase_result[$pn]+x}" ]]; then
            if [[ "${phase_result[$pn]}" == "true" ]]; then
                log "SUCCESS" "$pl: PASSED"
            else
                log "ERROR" "$pl: FAILED"
                any_failed=true
            fi
        fi
    done

    log "INFO" "Full log: $LOG_FILE"
    echo -e "${MAGENTA}============================================================${NC}"

    if [[ "$any_failed" == "true" ]]; then
        exit 1
    else
        exit 0
    fi
}

main "$@"
