#!/usr/bin/env bash
# scripts/preflight.sh — stage per-target config, run smoke tests, optionally kick off.
#
# Each target keeps its own factory.yaml and .env. This script copies them
# into shipyard root, runs smoke tests, and prompts before starting the
# build. If you decline, staged files stay in place and the script prints
# the command to run when you're ready.
#
# If a previously-staged shipyard/factory.yaml or shipyard/.env exists,
# it's renamed to <name>.old and the new one is staged in. .old files are
# just recovery breadcrumbs — the source of truth lives in each target.
#
# Usage:
#   bash scripts/preflight.sh <target-dir>
#   bash scripts/preflight.sh <target-dir> --resume
#
# Required files:
#   <target>/factory.yaml          per-target factory config (template: shipyard/factory.yaml.example)
#   <target>/.env                  per-target env vars        (template: shipyard/.env.target.example)
#   shipyard/.env.shared           operator-level secrets     (template: shipyard/.env.shared.example)

set -euo pipefail

# ---------- Args ----------
if [ $# -lt 1 ]; then
    echo "Usage: bash scripts/preflight.sh <target-dir> [--resume]" >&2
    exit 64
fi
TARGET_DIR_RAW="$1"
shift

# ---------- Paths ----------
SHIPYARD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [ ! -d "$TARGET_DIR_RAW" ]; then
    echo "ERROR: target dir does not exist: $TARGET_DIR_RAW" >&2
    exit 65
fi
TARGET_DIR="$(cd "$TARGET_DIR_RAW" && pwd)"

TARGET_YAML="$TARGET_DIR/factory.yaml"
TARGET_ENV="$TARGET_DIR/.env"
SHARED_ENV="$SHIPYARD_DIR/.env.shared"
STAGED_YAML="$SHIPYARD_DIR/factory.yaml"
STAGED_ENV="$SHIPYARD_DIR/.env"

# ---------- Back up any pre-existing staged files ----------
# If shipyard/factory.yaml or shipyard/.env already exist (from a previous
# preflight you didn't proceed with, or from a different target you staged
# earlier), rename them to .old before staging the current target. .old is
# just a recovery breadcrumb — the source of truth is each target's own
# factory.yaml and .env.
for staged in "$STAGED_YAML" "$STAGED_ENV"; do
    if [ -f "$staged" ]; then
        echo "▶ Renaming existing $(basename "$staged") → $(basename "$staged").old"
        mv -f "$staged" "${staged}.old"
    fi
done

# ---------- Validate inputs ----------
echo "▶ Validating target setup at $TARGET_DIR"
[ -f "$TARGET_YAML" ] \
    || { echo "ERROR: missing $TARGET_YAML — copy from shipyard/factory.yaml.example" >&2; exit 66; }
[ -f "$TARGET_ENV" ] \
    || { echo "ERROR: missing $TARGET_ENV — copy from shipyard/.env.target.example" >&2; exit 67; }
[ -f "$SHARED_ENV" ] \
    || { echo "ERROR: missing $SHARED_ENV — copy from shipyard/.env.shared.example and fill in" >&2; exit 68; }
[ -f "$TARGET_DIR/_bmad-output/planning-artifacts/epics.md" ] \
    || { echo "ERROR: missing $TARGET_DIR/_bmad-output/planning-artifacts/epics.md" >&2; exit 69; }
echo "  ✓ target dir + factory.yaml + .env + .env.shared + epics.md all present"

# ---------- Stage config ----------
echo "▶ Staging factory.yaml from $TARGET_YAML"
cp "$TARGET_YAML" "$STAGED_YAML"

echo "▶ Building shipyard/.env from .env.shared + $TARGET_ENV"
{
    echo "# AUTO-GENERATED by scripts/preflight.sh — do not edit; regenerated each run."
    echo "# To make persistent changes, edit either:"
    echo "#   - shipyard/.env.shared             (operator-level, all targets)"
    echo "#   - $TARGET_ENV   (target-level)"
    echo ""
    echo "# ----- Shared (operator-level) -----"
    cat "$SHARED_ENV"
    echo ""
    echo "# ----- Target-level (from $TARGET_ENV) -----"
    cat "$TARGET_ENV"
} > "$STAGED_ENV"

# ---------- Cleanup trap (mutation-only — staged files are kept in place) ----------
cleanup() {
    EXIT_CODE=$?
    # If something mutated factory.yaml mid-run (save_ci_fix_pre_existing
    # persists the brownfield/greenfield toggle), copy the change back to
    # the target so it isn't lost the next time the source is re-staged.
    if [ -f "$STAGED_YAML" ] && [ -f "$TARGET_YAML" ] \
       && ! diff -q "$STAGED_YAML" "$TARGET_YAML" >/dev/null 2>&1; then
        echo ""
        echo "▶ factory.yaml changed during run — syncing back to $TARGET_YAML"
        cp "$STAGED_YAML" "$TARGET_YAML"
    fi
    exit $EXIT_CODE
}
trap cleanup EXIT

# ---------- Smoke tests ----------
echo ""
echo "▶ Smoke tests"

if ! command -v claude >/dev/null 2>&1; then
    echo "ERROR: 'claude' CLI not on PATH" >&2; exit 70
fi
if ! claude --print "ready" --output-format text >/dev/null 2>&1; then
    echo "ERROR: 'claude --print' failed; run 'claude login' first" >&2; exit 71
fi
echo "  ✓ Claude Code authenticated"

# Venv check (best-effort — warn but don't block).
# Reminds the operator to activate the project venv if they haven't.
# Does not enforce — if deps are globally installed the factory will still run,
# but the next factory_imports check below will still catch a broken environment.
#
# Note: VIRTUAL_ENV may be spuriously set to a system Python path (e.g.
# 'c:\python314') by some installers — checking for pyvenv.cfg confirms
# the path is actually a venv.
VENV_OK=0
if [ -n "${VIRTUAL_ENV:-}" ] && [ -f "${VIRTUAL_ENV}/pyvenv.cfg" ]; then
    VENV_OK=1
fi
if [ "$VENV_OK" -eq 1 ]; then
    echo "  ✓ venv active: $VIRTUAL_ENV"
else
    if [ -f "$SHIPYARD_DIR/.venv/pyvenv.cfg" ]; then
        echo "  ⚠ No venv active (VIRTUAL_ENV='${VIRTUAL_ENV:-unset}'). Activate before kickoff:"
        echo "      source .venv/Scripts/activate     # Git Bash"
        echo "      .venv\\Scripts\\activate           # PowerShell / cmd"
    else
        echo "  ⚠ No .venv found at $SHIPYARD_DIR/.venv. Create with:"
        echo "      python -m venv .venv"
        echo "      source .venv/Scripts/activate"
        echo "      pip install -r requirements.txt -r requirements-dev.txt"
    fi
    echo "    (proceeding with whatever python is on PATH — see next check)"
fi

cd "$SHIPYARD_DIR"
if ! python -c "from src.main import main" >/dev/null 2>&1; then
    echo "ERROR: factory imports broken — activate .venv and 'pip install -r requirements.txt'?" >&2
    exit 72
fi
echo "  ✓ Factory imports cleanly"

# Relay health (best-effort — warn but don't block).
# Two-layer probe so a broken DB layer doesn't masquerade as healthy:
#   1. /health returns body containing "status":"ok"  — FastAPI app is up
#   2. /api/sessions returns a JSON list              — Postgres is reachable
RELAY_URL=$(grep -E '^SHIPYARD_RELAY_URL=' "$STAGED_ENV" | head -1 | cut -d= -f2- | tr -d '"')
if [ -n "$RELAY_URL" ]; then
    HEALTH_BODY=$(curl -sf --max-time 10 "$RELAY_URL/health" 2>/dev/null || echo "")
    if [ -z "$HEALTH_BODY" ]; then
        echo "  ⚠ Relay unreachable at $RELAY_URL — proceeding without dashboard"
    elif ! echo "$HEALTH_BODY" | grep -q '"status"[[:space:]]*:[[:space:]]*"ok"'; then
        echo "  ⚠ Relay /health returned unexpected body: $HEALTH_BODY — proceeding without dashboard"
    elif ! curl -sf --max-time 10 "$RELAY_URL/api/sessions" 2>/dev/null \
            | python -c "import json,sys; d=json.load(sys.stdin); sys.exit(0 if isinstance(d, list) else 1)" >/dev/null 2>&1; then
        echo "  ⚠ Relay app up but /api/sessions failed — DB layer unreachable; proceeding without dashboard"
    else
        echo "  ✓ Relay healthy at $RELAY_URL (app + DB reachable)"
    fi
fi

# Git remote (best-effort — warn but don't block)
GIT_REMOTE=$(grep -E '^GIT_REMOTE_ORIGIN=' "$STAGED_ENV" | head -1 | cut -d= -f2- | tr -d '"')
if [ -n "$GIT_REMOTE" ]; then
    if git ls-remote "$GIT_REMOTE" >/dev/null 2>&1; then
        echo "  ✓ Target git remote reachable"
    else
        echo "  ⚠ Cannot reach $GIT_REMOTE — pushes will fail mid-build"
    fi
fi

# ---------- Confirm before kickoff ----------
EXTRA_ARGS=""
[ "$#" -gt 0 ] && EXTRA_ARGS=" $*"

echo ""
echo "▶ All smoke tests passed."
echo "  Staged config:  $STAGED_YAML  (from $TARGET_YAML)"
echo "                  $STAGED_ENV   (from .env.shared + $TARGET_ENV)"
echo ""
read -r -p "Proceed with the build now? [y/N] " answer
case "${answer:-N}" in
    [yY]|[yY][eE][sS]) ;;
    *)
        cat <<EOF

Setup complete — no build started. Staged config left in place. To kick off when ready:

    cd $SHIPYARD_DIR
    python -m src.main --rebuild "$TARGET_DIR"$EXTRA_ARGS

If you re-run preflight for a DIFFERENT target before running that command,
the staged files will be renamed to .old and replaced — the kickoff command
above would then use the other target's config. Re-run preflight for this
target if that happens.
EOF
        exit 0
        ;;
esac

# ---------- Kick off ----------
echo ""
echo "▶ Starting rebuild"
echo ""
python -m src.main --rebuild "$TARGET_DIR" "$@"
